# Generated by Django 3.2.8 on 2021-10-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_name', models.CharField(max_length=100)),
                ('notice_date', models.DateField()),
                ('notice_subject', models.CharField(max_length=200)),
                ('notice_message', models.CharField(max_length=1000)),
            ],
        ),
    ]
