# Generated by Django 3.2.8 on 2021-10-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mods', '0002_delete_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_department', models.CharField(max_length=30)),
                ('alert_date', models.DateField()),
                ('alert_subject', models.CharField(max_length=100)),
                ('alert_body', models.CharField(max_length=1000)),
            ],
        ),
    ]
